MERGE INTO MPA_RATE KEY (MPA_RATE_ID, NAME) VALUES (1, 'G');
MERGE INTO MPA_RATE KEY (MPA_RATE_ID, NAME) VALUES (2, 'PG');
MERGE INTO MPA_RATE KEY (MPA_RATE_ID, NAME) VALUES (3, 'PG-13');
MERGE INTO MPA_RATE KEY (MPA_RATE_ID, NAME) VALUES (4, 'R');
MERGE INTO MPA_RATE KEY (MPA_RATE_ID, NAME) VALUES (5, 'NC-17');

MERGE INTO GENRE KEY (GENRE_ID, NAME) VALUES (1, 'Комедия');
MERGE INTO GENRE KEY (GENRE_ID, NAME) VALUES (2, 'Драма');
MERGE INTO GENRE KEY (GENRE_ID, NAME) VALUES (3, 'Мультфильм');
MERGE INTO GENRE KEY (GENRE_ID, NAME) VALUES (4, 'Триллер');
MERGE INTO GENRE KEY (GENRE_ID, NAME) VALUES (5, 'Документальный');
MERGE INTO GENRE KEY (GENRE_ID, NAME) VALUES (6, 'Боевик');

INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASEDATE, DURATION, RATE, MPA_RATE_ID)
VALUES ('Название1', 'Описание1', '1994-03-04', 100, 4, 1);

INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASEDATE, DURATION, RATE, MPA_RATE_ID)
VALUES ('Название2', 'Описание2', '2001-03-04', 120, 5, 2);

INSERT INTO USERS(EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES ('asd@gmail.com', 'Асд', 'Кверт', '1994-03-04');

INSERT INTO USERS(EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES ('qwer@gmail.com', 'Кверт', 'АСД', '1997-04-14');

INSERT INTO LIKES(USER_ID, FILM_ID)
VALUES (1, 2);

INSERT INTO FRIENDS(USER_ID, FRIEND_ID)
VALUES (1, 2);

INSERT INTO FILM_GENRE(FILM_ID, GENRE_ID)
VALUES (1, 1);

INSERT INTO FILM_GENRE(FILM_ID, GENRE_ID)
VALUES (1, 2);

INSERT INTO FILM_GENRE(FILM_ID, GENRE_ID)
VALUES (2, 3);



