INSERT INTO PUBLIC.MPA_RATE (NAME)
VALUES ('G');

INSERT INTO PUBLIC.MPA_RATE (NAME)
VALUES ('PG');

INSERT INTO PUBLIC.MPA_RATE (NAME)
VALUES ('PG-13');

INSERT INTO PUBLIC.MPA_RATE (NAME)
VALUES ('R');

INSERT INTO PUBLIC.MPA_RATE (NAME)
VALUES ('NC-17');

INSERT INTO PUBLIC.GENRE (NAME)
VALUES ('Комедия');

INSERT INTO PUBLIC.GENRE (NAME)
VALUES ('Драма');

INSERT INTO PUBLIC.GENRE (NAME)
VALUES ('Мультфильм');

INSERT INTO PUBLIC.GENRE (NAME)
VALUES ('Триллер');

INSERT INTO PUBLIC.GENRE (NAME)
VALUES ('Документальный');

INSERT INTO PUBLIC.GENRE (NAME)
VALUES ('Боевик');

